# orchestrate infracstructure containers
kubectl apply -f ./k8s/infrastructure/discovery-server/
kubectl apply -f ./k8s/infrastructure/api-gateway/
kubectl apply -f ./k8s/infrastructure/grafana/
kubectl apply -f ./k8s/infrastructure/kafka/
kubectl apply -f ./k8s/infrastructure/keycloak/
kubectl apply -f ./k8s/infrastructure/keycloak-mysql/
kubectl apply -f ./k8s/infrastructure/mongodb/
kubectl apply -f ./k8s/infrastructure/postgres-inventory/
kubectl apply -f ./k8s/infrastructure/postgres-order/
kubectl apply -f ./k8s/infrastructure/prometheus/
kubectl apply -f ./k8s/infrastructure/zipkin/
kubectl apply -f ./k8s/infrastructure/zookeeper/

# orchestrate services containers
kubectl apply -f ./k8s/services/inventory-service/
kubectl apply -f ./k8s/services/notification-service/
kubectl apply -f ./k8s/services/order-service/
kubectl apply -f ./k8s/services/product-service/